services:
  todolist-environment:
    container_name: todolist-environment
    env_file: ./.env.docker
    build:
      context: .
    ports:
      - 8081:8080
    depends_on:
      - postgres
    
  postgres:
    image: postgres:17
    env_file:
    - ./.env.docker
    restart: "always"
    environment:
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: